# Generated by Django 4.2 on 2025-07-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('masters', '0002_memo_historicalmemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='college',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user__usertype': 'College'}, to='users.userprofile'),
        ),
    ]
