# Generated by Django 4.2 on 2025-08-06 11:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_memo_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequestsubmission',
            name='alternative_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestsubmission',
            name='alternative_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
