# Generated by Django 4.2 on 2025-08-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_historicalrequestsubmission_alternative_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequestsubmission',
            name='status',
            field=models.CharField(choices=[('re_assign', 'Re Assign'), ('forwarded', 'Forwarded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='forwarded', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalrequestsubmissionstatushistory',
            name='status',
            field=models.CharField(choices=[('re_assign', 'Re Assign'), ('forwarded', 'Forwarded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='forwarded', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestsubmission',
            name='status',
            field=models.CharField(choices=[('re_assign', 'Re Assign'), ('forwarded', 'Forwarded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='forwarded', max_length=30),
        ),
        migrations.AlterField(
            model_name='requestsubmissionstatushistory',
            name='status',
            field=models.CharField(choices=[('re_assign', 'Re Assign'), ('forwarded', 'Forwarded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='forwarded', max_length=20),
        ),
    ]
