# Generated by Django 4.2 on 2025-08-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_historicalrequestsubmission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequestsubmission',
            name='current_usertype',
            field=models.CharField(choices=[('CRO', 'Community Relation Officer'), ('OE', 'Office Executive'), ('PRO', 'Public Relation Officer'), ('CAO', 'Chief Academic Officer'), ('director', 'Director'), ('AC', 'Admin Coordinator'), ('AA', 'Assistant Administrator'), ('FO', 'Finance Officer'), ('College', 'College')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequestsubmissionstatushistory',
            name='next_usertype',
            field=models.CharField(choices=[('CRO', 'Community Relation Officer'), ('OE', 'Office Executive'), ('PRO', 'Public Relation Officer'), ('CAO', 'Chief Academic Officer'), ('director', 'Director'), ('AC', 'Admin Coordinator'), ('AA', 'Assistant Administrator'), ('FO', 'Finance Officer'), ('College', 'College')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalrequestsubmissionstatushistory',
            name='usertype',
            field=models.CharField(choices=[('CRO', 'Community Relation Officer'), ('OE', 'Office Executive'), ('PRO', 'Public Relation Officer'), ('CAO', 'Chief Academic Officer'), ('director', 'Director'), ('AC', 'Admin Coordinator'), ('AA', 'Assistant Administrator'), ('FO', 'Finance Officer'), ('College', 'College')], max_length=30),
        ),
        migrations.AlterField(
            model_name='requestsubmission',
            name='current_usertype',
            field=models.CharField(choices=[('CRO', 'Community Relation Officer'), ('OE', 'Office Executive'), ('PRO', 'Public Relation Officer'), ('CAO', 'Chief Academic Officer'), ('director', 'Director'), ('AC', 'Admin Coordinator'), ('AA', 'Assistant Administrator'), ('FO', 'Finance Officer'), ('College', 'College')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='requestsubmissionstatushistory',
            name='next_usertype',
            field=models.CharField(choices=[('CRO', 'Community Relation Officer'), ('OE', 'Office Executive'), ('PRO', 'Public Relation Officer'), ('CAO', 'Chief Academic Officer'), ('director', 'Director'), ('AC', 'Admin Coordinator'), ('AA', 'Assistant Administrator'), ('FO', 'Finance Officer'), ('College', 'College')], max_length=30),
        ),
        migrations.AlterField(
            model_name='requestsubmissionstatushistory',
            name='usertype',
            field=models.CharField(choices=[('CRO', 'Community Relation Officer'), ('OE', 'Office Executive'), ('PRO', 'Public Relation Officer'), ('CAO', 'Chief Academic Officer'), ('director', 'Director'), ('AC', 'Admin Coordinator'), ('AA', 'Assistant Administrator'), ('FO', 'Finance Officer'), ('College', 'College')], max_length=30),
        ),
    ]
