# Generated by Django 4.2 on 2025-08-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('masters', '0006_alter_historicalrequestsubmission_current_usertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsubmission',
            name='request_shared_usertype',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_requests', to='users.userprofile'),
        ),
    ]
