# Generated by Django 4.2 on 2025-08-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('masters', '0008_alter_requestsubmission_request_shared_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsubmission',
            name='request_shared_usertype',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('user__usertype', 'College'), _negated=True), related_name='shared_requests', to='users.userprofile'),
        ),
    ]
