# Generated by Django 4.2 on 2025-08-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_alter_requestsubmission_request_shared_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestsubmission',
            old_name='request_shared_usertype',
            new_name='request_shared_user',
        ),
    ]
