# Generated by Django 4.2 on 2025-08-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_rename_request_shared_usertype_requestsubmission_request_shared_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestsubmission',
            old_name='request_shared_user',
            new_name='request_shared_usertype',
        ),
    ]
