# Generated by Django 4.2 on 2025-08-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('masters', '0011_rename_request_shared_user_requestsubmission_request_shared_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequestsubmission',
            name='college',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='historicalrequestsubmission',
            name='status',
            field=models.CharField(choices=[('forwarded', 'Forwarded'), ('re_assign', 'Re Assign'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='forwarded', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalrequestsubmissionstatushistory',
            name='status',
            field=models.CharField(choices=[('forwarded', 'Forwarded'), ('re_assign', 'Re Assign'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='forwarded', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestsubmission',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='requestsubmission',
            name='status',
            field=models.CharField(choices=[('forwarded', 'Forwarded'), ('re_assign', 'Re Assign'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='forwarded', max_length=30),
        ),
        migrations.AlterField(
            model_name='requestsubmissionstatushistory',
            name='status',
            field=models.CharField(choices=[('forwarded', 'Forwarded'), ('re_assign', 'Re Assign'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='forwarded', max_length=20),
        ),
    ]
