# Generated by Django 4.2 on 2025-08-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('masters', '0012_alter_historicalrequestsubmission_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsubmission',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='college', to='users.userprofile'),
        ),
    ]
