# Generated by Django 4.2 on 2025-08-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('CRO', 'Community Relation Officer'), ('OE', 'Office Executive'), ('PRO', 'Public Relation Officer'), ('CAO', 'Chief Academic Officer'), ('director', 'Director'), ('AC', 'Admin Coordinator'), ('AA', 'Assistant Administrator'), ('FO', 'Finance Officer'), ('College', 'College')], max_length=30, verbose_name='Permissions'),
        ),
    ]
